INSERT INTO Cargo (idCargo, nombre, flexible) VALUES (1, 'Secretaria', 0);
INSERT INTO Cargo (idCargo, nombre, flexible) VALUES (2, 'Revisor de juegos', 1);
INSERT INTO Cargo (idCargo, nombre, flexible) VALUES (3, 'Obrero', 0);
INSERT INTO Cargo (idCargo, nombre, flexible) VALUES (4, 'Supervisor', 0);
INSERT INTO Cargo (idCargo, nombre, flexible) VALUES (5, 'Contador', 0);
INSERT INTO Cargo (idCargo, nombre, flexible) VALUES (6, 'Auditor', 0);
INSERT INTO Cargo (idCargo, nombre, flexible) VALUES (7, 'Seguridad', 0);
INSERT INTO Cargo (idCargo, nombre, flexible) VALUES (8, 'Almacenero', 0);
INSERT INTO Cargo (idCargo, nombre, flexible) VALUES (9, 'Limpieza', 1);
INSERT INTO Cargo (idCargo, nombre, flexible) VALUES (10, 'Administrador de sistemas', 1);
INSERT INTO Cargo (idCargo, nombre, flexible) VALUES (11, 'Distribuidor', 0);
INSERT INTO Cargo (idCargo, nombre, flexible) VALUES (12, 'Chofer', 1);
INSERT INTO Cargo (idCargo, nombre, flexible) VALUES (13, 'Diseñador', 1);
INSERT INTO Cargo (idCargo, nombre, flexible) VALUES (14, 'Marketing', 1);
INSERT INTO Cargo (idCargo, nombre, flexible) VALUES (15, 'Editor', 1);
INSERT INTO Cargo (idCargo, nombre, flexible) VALUES (16, 'Prensista', 0);
INSERT INTO Cargo (idCargo, nombre, flexible) VALUES (17, 'Publicista', 1);
INSERT INTO Cargo (idCargo, nombre, flexible) VALUES (18, 'Vendedor', 1);
INSERT INTO Cargo (idCargo, nombre, flexible) VALUES (19, 'Director de produccion', 1);