INSERT INTO Feriado (idFeriado, fecha, nombre) VALUES (1, '2019-01-01', 'Año nuevo');
INSERT INTO Feriado (idFeriado, fecha, nombre) VALUES (2, '2019-01-22', 'fundacion del estado Plurinacional de Bolivia');
INSERT INTO Feriado (idFeriado, fecha, nombre) VALUES (3, '2019-03-04', 'Carnaval');
INSERT INTO Feriado (idFeriado, fecha, nombre) VALUES (4, '2019-03-05', 'Carnaval');
INSERT INTO Feriado (idFeriado, fecha, nombre) VALUES (5, '2019-05-19', 'Viernes Santo');
INSERT INTO Feriado (idFeriado, fecha, nombre) VALUES (6, '2019-05-01', 'Dia del trajajo');
INSERT INTO Feriado (idFeriado, fecha, nombre) VALUES (7, '2019-06-20', 'Corpus Christi');
INSERT INTO Feriado (idFeriado, fecha, nombre) VALUES (8, '2019-06-21', 'Año nuevo aymara');
INSERT INTO Feriado (idFeriado, fecha, nombre) VALUES (9, '2019-08-06', 'Dia de la independencia de Bolivia');
INSERT INTO Feriado (idFeriado, fecha, nombre) VALUES (10, '2019-09-14', 'Dia del departamento de Cochabmba');
INSERT INTO Feriado (idFeriado, fecha, nombre) VALUES (11, '2019-11-02', 'Dia de todos los santos');
INSERT INTO Feriado (idFeriado, fecha, nombre) VALUES (12, '2019-12-25', 'Navidad');